const FONTS = [
    'Arial',
    'Arial Black',
    'Calibri',
    'Comic Sans',
    'Courier',
    'Courier New',
    'Franklin Gothic Medium',
    'Georgia',
    'Impact',
    'Lucida Console',
    'Marlett',
    'Modern',
    'Script',
    'Serif',
    'Segoe UI',
    'Symbol',
    'Tahoma',
    'Times New Roman',
    'Trebuchet',
]